# Release Drafter configuration for changelog categories, autolabeling, and semantic version resolution.

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What Changed 👀
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: 🧪 Test
    labels:
      - test
  - title: 👷 CI
    labels:
      - ci
  - title: ♻️ Refactor
    labels:
      - changed
      - enhancement
      - refactor
  - title: ⛔️ Deprecated
    labels:
      - deprecated
  - title: 🔐 Security
    labels:
      - security
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
  - title: 🧩 Dependency Updates
    labels:
      - deps
      - dependencies
  - title: 🧰 Maintenance
    label: 'chore'
  - title: 📝 Other changes
autolabeler:
  - label: 'chore'
    branch:
      - '/(chore)\/.*/'
  - label: 'security'
    branch:
      - '/(security)\/.*/'
  - label: 'refactor'
    branch:
      - '/(refactor)\/.*/'
  - label: 'docs'
    branch:
      - '/(docs)\/.*/'
  - label: 'ci'
    branch:
      - '/(ci)\/.*/'
  - label: 'test'
    branch:
      - '/(test)\/.*/'
  - label: 'bug'
    branch:
      - '/(fix)\/.*/'
  - label: 'feature'
    branch:
      - '/(feat)\/.*/'
  - label: 'minor'
    branch:
      - '/(feat)\/.*/'
  - label: 'patch'
    branch:
      - '/(fix)\/.*/'
    body:
      - '/JIRA-[0-9]{1,4}/'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

exclude-labels:
  - skip-changelog
