services:
  prometheus:
    image: prom/prometheus:v3.10.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./../configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-remote-write-receiver"
      - "--log.level=debug"
    networks:
      - booking

  tempo:
    image: grafana/tempo:2.10.1
    container_name: tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./../configs/tempo.yaml:/etc/tempo.yaml
    expose:
      - "3200"
      - "9095"
      - "4317"
      - "4318"
    networks:
      - booking

  loki:
    image: grafana/loki:3.6.7
    hostname: loki
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./../configs/loki-config.yaml:/etc/loki/local-config.yaml
    expose:
      - "3100"
      - "9096"
    networks:
      - booking

  grafana:
    image: grafana/grafana:12.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./../configs/grafana/provisioning:/etc/grafana/provisioning
      - ./../configs/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - booking

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.147.0
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./../configs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "11888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    environment:
      ASPIRE_OTLP_ENDPOINT: http://aspire-dashboard:18889
      ASPIRE_API_KEY: your_api_key
      PROMETHEUS_ENDPOINT: 0.0.0.0:8889
      PROMETHEUS_REMOTE_WRITE_ENDPOINT: http://prometheus:9090/api/v1/write
      LOKI_ENDPOINT: http://loki:3100/otlp
      TEMPO_ENDPOINT: http://tempo:4317
    networks:
      - booking

  identity:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started

  flight:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started

  passenger:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started

  booking:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started

  payment:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
